### PR TITLE
Add support of adding custom conditions out of library

### PR DESCRIPTION
**Pull request by promix17**
Signed-off-by: Mikhail Pronyakin <pronyakin@onsec.ru>

### CODE REVIEW

**Comment by arekkas** [comment]
I really like the idea! I think there are some things here that need consideration:

* We could simply make `conditionFactories` public by writing it upper case
* Rename `AddCustomCondition` to `AddConditionFactory`

What do you think?

**Comment by promix17** [comment]
I've changed conditionFactories to ConditionFactories and AddCustomCondition to AddConditionFactory.

I've also updated README.md to let users know about this option.

**Comment by arekkas** [comment]
Thank you, I think you can remove `AddConditionFactory` as it is easy enough to do:

```go
ladon.conditionFactories["foo"] = bar
```

Do you agree?

**Comment by promix17** [comment]
Yes, that's enough. Fixed this.

**Comment by arekkas** [comment]
Awesome, thank you for your contribution!

**Pull request merged**
